CREATE DATABASE IF NOT EXISTS opencart DEFAULT CHARACTER SET utf8mb4;
CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'opencart';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
USE opencart;
SOURCE /tmp/vend_db.sql;
